# -*- coding: utf-8 -*-
"""Prelim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gbEpG4TGsFGwHrgcUlYijfQXGsoWTI7
"""

import pandas as pd
from google.colab import files

# Upload CSV
uploaded = files.upload()
filename = next(iter(uploaded))
df = pd.read_csv(filename)

print("SUS Dataset")
print(df)

#SUS Questions Columns
sus_columns = [f"Q{i}" for i in range (1,11)]


#Calculate SUS Score
def calculate_sus_score(row):
  score = 0
    #Odd or Even items
  for i, col in enumerate(sus_columns,start=1):
    response =row[col]

    #Odd item
    if i%2 == 1:
      score += response -1
    #Even item
    else:
      score += 5 - response
  return score * 2.5
#Display computed SUS Scores
df["sus_score"] = df.apply(calculate_sus_score,axis=1)
print("\nIndividual SUS Scores")
if "user" in df.columns:
  print(df[["user","sus_score"]])
else:
  print(df[["sus_score"]])